"""Make PK autoincrement

Revision ID: 4806373fe6ba
Revises: 2850968d00f5
Create Date: 2024-07-10 16:51:33.748912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4806373fe6ba'
down_revision: Union[str, None] = '2850968d00f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fill_form_id', table_name='fill_form')
    op.drop_table('fill_form')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fill_form',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fill_form_pkey')
    )
    op.create_index('ix_fill_form_id', 'fill_form', ['id'], unique=False)
    # ### end Alembic commands ###
