"""Change data type for question column

Revision ID: 7ce7e06aa20c
Revises: 39c7574df316
Create Date: 2024-07-09 17:16:18.848725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce7e06aa20c'
down_revision: Union[str, None] = '39c7574df316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fill_form', 'question',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False, postgresql_using='question::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fill_form', 'question',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False, postgresql_using='question::text')
    # ### end Alembic commands ###
