"""Fix variables

Revision ID: 978b5142f7b3
Revises: f153056f7e03
Create Date: 2024-07-10 16:00:18.126227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978b5142f7b3'
down_revision: Union[str, None] = 'f153056f7e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question')
    # ### end Alembic commands ###
